FROM node:16-alpine3.15

RUN apk update && \
    apk --no-cache add git && \
    npm i -g npm@7.18.1	&& \
    npm i -g @nestjs/cli

WORKDIR /app

COPY *.json .
RUN npm ci

EXPOSE 3001

CMD [ "npm", "run", "dev" ]